### PR TITLE
修改边界多边形的isHighCenter判断

### PR DESCRIPTION
**Pull request by jinfengg**
王老师，您好！此处多边型的高值中心应该是写反了。例如min == Double.MIN_VALUE时，说明等值线的值都是高于边界的值的，此时边界这块多边形的IsHighCenter应该为false；max == Double.MAX_VALUE时，等值线的值都是低于边界的值的，此时边界多边形的IsHighCenter应该为true。不过此处生成的min值后面会赋值到边界多边形的LowValue字段，但是min值是边界中的值，不在_CValues数组中；在 DrawingPanel类中，绘制的时候是通过匹配_CValues中的位置，来获得颜色的，这样有可能会匹配不到，是不是要在此处直接修正min和max为_CValues中的值，或者获取颜色索引的时候进行判断。

### CODE REVIEW

**Comment by Yaqiang** [comment]
This is a very special condition when no contour intersect with border line, so we need to construct a ring-shape border polygon. In this condition, the high center judgement is different with the boder polygons containing boder intersection contour lines.

**Comment by jinfengg** [comment]
就是这种特殊情况出现了，我才发现此处的问题的。下图是用能见度绘制，4条红色等值线形成的多边形，圈内的值都是小于圈外的，图中格点的能见度数值（蓝色字体）是除以1000进行标记的，图是4k分辨率截图的，可以点击看大图。
image

此时4条等值线的值都是低于边界的值的，max = Double.MAX_VALUE，然后代码中边界多边形的IsHighCenter根据这个判断设置为了false。
这时候生成的5个多边形的IsHighCenter都为false，这样就导致了最大的多边形所取颜色也跟另外4个小的一样了。
```
这里是5个多边形的高低值以及IsHighCenter值
LowValue--HighValue--IsHighCenter
10000.0--27944.228744036962--false
10000.0--10000.0--false
10000.0--10000.0--false
10000.0--10000.0--false
10000.0--10000.0--false
```

我将代码中的IsHighCenter修改后，图形颜色才能正常区分。

**Comment by Yaqiang** [comment]
Could you provide an example which can be reproduced from my side?

**Comment by jinfengg** [comment]
_CValues 值是 50,200,500,1000,10000
插值方法是Interpolate.interpolation_IDW_Neighbor(discreteData, X, Y, 8, undefData)，
gridXY是96、128
地图边界可以用src\test\resources\sample\shanghai.wmp，之前上传过
能见度数据如下，
idx,Lontitude,Latitude,Precipitation
0,121.30306,31.06694,65535
1,121.12167,31.00083,65535
2,121.78667,31.36389,40552
3,121.79333,31.37111,40443
4,121.36389,31.48833,38427
5,121.50889,31.39250,35000
6,121.67500,31.14694,34883
7,121.65222,31.66583,34825
8,121.36583,31.10306,30000
9,120.95583,31.08417,29269
10,121.78333,31.05000,28969
11,121.81472,31.57778,27310
12,121.47583,31.11111,25340
13,121.49972,30.88500,22805
14,121.28528,31.23000,22263
15,121.53333,31.23333,21377
16,121.07389,30.92694,20000
17,121.50444,31.39028,20000
18,121.47806,31.19361,20000
19,121.55667,31.27278,20000
20,121.88278,31.00750,19990
21,121.53500,30.83361,19990
22,121.34444,31.45333,19876
23,121.70472,31.18917,19519
24,121.16417,31.13722,19421
25,121.06389,30.95222,19384
26,121.43167,31.19222,19045
27,121.10139,31.25083,18489
28,121.70917,31.40250,17281
29,121.00222,31.05194,16599
30,121.57139,31.37500,15980
31,121.44472,31.39083,15606
32,121.49139,31.24750,15512
33,121.49278,31.66639,15490
34,121.84667,30.85278,15290
35,121.19944,31.38056,15220
36,121.17583,31.02000,14404
37,121.27333,30.81611,14394
38,121.12194,31.13417,13689
39,121.28056,31.16333,13662
40,121.24556,31.22583,11276
41,121.23917,31.71417,11116
42,121.18917,31.09639,10361
43,121.13806,30.87194,9880
44,121.54472,30.99722,9079
45,121.24444,31.25139,8352
46,121.46083,31.06500,6899
47,121.56056,31.27833,2000

**Comment by Yaqiang** [comment]
非常感谢你的 RP 提交，但这个 RP 缺乏详细的说明和测试。如果你确实认为这个 RP 有价值，可以先在 gitter 上讨论（https://gitter.im/meteoinfo/community）。

**Comment by jinfengg** [comment]
好的，我目前提交了测试代码，可能这样会好看点。
1、启动类是WContourShanghaiDemo。能见度图层是在 Sample->Interpolation->IDW_Neighbour菜单下。
2、勾选Grid Data可以显示格点的数据，我把数值除以1000后进行隔列展示，跟图例对比时，图中数值需要乘以1000，
3、图中能看到4个圆圈的颜色能正常显示，这是基于上次修改的结果。老师您可以尝试用旧代码进行测试，就会发现这4个圈的颜色变成深色的，也就是跟外面一样，根据图例级别，是显示错误的。
image

**Comment by jinfengg** [comment]
1、另外我还提交了一个判断两个线段相交方法的修改，在运行中发现一些图层裁剪的时候有错误。
2、原代码中方法isLineSegmentCross判断线段AB和CD，会认为这两个线段相交，而且getCrossPoint方法会计算中X是两个线段的焦点。
3、测试数据如下：
_Line lineA = new Line();
        PointD A= new PointD(113.48715850316847,22.040105609579197 );
        PointD B= new PointD(113.48725540262005,22.040578992068422 );
        lineA.P1 = A;
        lineA.P2 = B;
        Line lineB = new Line();
        PointD C= new PointD(113.486328,22.04248 );
        PointD D= new PointD(113.487915, 22.040527 );
        lineB.P1 = C;
        lineB.P2 = D;_
image

4、目前我只是修改了isLineSegmentCross的方法，里面的判断是参照turf.js的源码中的方法，
https://github.com/Turfjs/turf/blob/fcdaa939c905e6cfa80cca11a0e7cbb851ad1a47/packages/turf-line-intersect/index.ts#L31
源码如下
_/**
 * Find a point that intersects LineStrings with two coordinates each
 *
 * @private
 * @param {Feature<LineString>} line1 GeoJSON LineString (Must only contain 2 coordinates)
 * @param {Feature<LineString>} line2 GeoJSON LineString (Must only contain 2 coordinates)
 * @returns {Feature<Point>} intersecting GeoJSON Point
 */
function intersects(line1: Feature<any>, line2: Feature<any>) {
  const coords1: any = getCoords(line1);
  const coords2: any = getCoords(line2);
  if (coords1.length !== 2) {
    throw new Error("<intersects> line1 must only contain 2 coordinates");
  }
  if (coords2.length !== 2) {
    throw new Error("<intersects> line2 must only contain 2 coordinates");
  }
  const x1 = coords1[0][0];
  const y1 = coords1[0][1];
  const x2 = coords1[1][0];
  const y2 = coords1[1][1];
  const x3 = coords2[0][0];
  const y3 = coords2[0][1];
  const x4 = coords2[1][0];
  const y4 = coords2[1][1];
  const denom = (y4 - y3) * (x2 - x1) - (x4 - x3) * (y2 - y1);
  const numeA = (x4 - x3) * (y1 - y3) - (y4 - y3) * (x1 - x3);
  const numeB = (x2 - x1) * (y1 - y3) - (y2 - y1) * (x1 - x3);

  if (denom === 0) {
    if (numeA === 0 && numeB === 0) {
      return null;
    }
    return null;
  }

  const uA = numeA / denom;
  const uB = numeB / denom;

  if (uA >= 0 && uA <= 1 && uB >= 0 && uB <= 1) {
    const x = x1 + uA * (x2 - x1);
    const y = y1 + uA * (y2 - y1);
    return point([x, y]);
  }
  return null;
}_

**Pull request merged**
